apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-prometheus-pv2
  labels:
    type: local
spec: 
  storageClassName: manual
  capacity: 
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/vagrant/prometheus/data2"