apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-pv1
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi