apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-grafana-pv1
  labels:
    type: local
spec: 
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/vagrant/grafana/data"