apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-jenkins-pv1
  labels:
    type: local
spec: 
  storageClassName: manual
  capacity: 
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/vagrant/data"