apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-pv1
spec: 
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi